# Generated by Django 4.1.7 on 2023-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0002_alter_recipe_image_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=50000),
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
